
CREATE TABLE FUND_NAV(
	D_DATE TEXT NOT NULL,
	C_FUNDCODE TEXT NOT NULL,
	C_FUNDNAME TEXT NOT NULL,
	F_NAV REAL NOT NULL
);


CREATE TABLE FUND_INFO(
	C_FUNDCODE text NOT NULL,
	C_FUNDNAME text NOT NULL,
	C_FUNDTYPE TEXT NOT NULL,
	D_START_DATE TEXT,
	D_END_DATE TEXT 
);

